### ISSUE TITLE
Output option bug in tesseract_recognize_api.py

### ISSUE THREAD

**Issue by nachtgold** [mauvilsa/tesseract-recognize#5]
I think, I found a little bug in your python wrapper. In your curl sample is an output file named. The script `tesseract_recognize_api.py` places the value in the command, but forgets the `-o` (which seems to expected by `tesseract-recognize.cc`)

I received the following error
> execution failed: command=/usr/local/bin/tesseract-recognize /DATA/img.png /DATA/img3.xml output=tesseract-recognize: error: only a single page xml allowed as input

The flag can be included in the value to workaround it like `curl -s -X POST -H "Content-Type: application/json" -d '{"input_file":"/DATA/img.png","output_file":"-o /DATA/img3.xml"}' http://localhost:5000/tesseract-recognize`

**Comment by mauvilsa** [comment]
@nachtgold thank you for reporting this. I will fix this as soon as I can, most likely after Christmas break.

**Comment by mauvilsa** [comment]
@nachtgold the `tesseract_recognize_api.py` script was only an initial version that was not used much, which is why it wasn't being maintained. Furthermore, it wasn't too useful as a microservice since it required the files be locally available inside the docker container. Because of this instead of fixing the bug I have completely changed `tesseract_recognize_api.py`. Please have a look at the latest version and let me know what you think.

**Comment by nachtgold** [comment]
I tried following new option:

```
docker pull mauvilsa/tesseract-recognize:2020.01.13-ubuntu18.04-pkg
docker run --rm -t -p 5000:5000 mauvilsa/tesseract-recognize:2020.01.13-ubuntu18.04-pkg
```
And then
```
curl -o output.xml -F images=@4783992675_4c6361d4d5_z.png -F options='["--layout", "word"]' http://localhost:5000/tesseract-recognize/process
```

This is what happend:
```
2020-01-13 22:31:53,694 - tesseract_recognize_api.py - INFO - Loaded default values from parser.
2020-01-13 22:31:53,694 - tesseract_recognize_api.py - INFO - Parsed environment variables.
2020-01-13 22:31:53,695 - tesseract_recognize_api.py - INFO - Parsed arguments.
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-01-13 22:32:49,670 - tesseract_recognize_api.py - ERROR - Exception on /tesseract-recognize/process [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 131, in read_chunk_len
    _len = int(line.strip(), 16)
ValueError: invalid literal for int() with base 16: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 131, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 253, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 584, in parse
    return self.cls(form), self.cls(files)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/datastructures.py", line 420, in __init__
    for key, value in mapping or ():
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 582, in <genexpr>
    form = (p[1] for p in formstream if p[0] == "form")
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 537, in parse_parts
    for ellt, ell in self.parse_lines(file, boundary, content_length):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 451, in parse_lines
    terminator = self._find_terminator(iterator)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 368, in _find_terminator
    for line in iterator:
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 721, in make_line_iter
    first_item = next(_iter, "")
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 681, in _make_chunk_iter
    item = _read(buffer_size)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 144, in readinto
    self._len = self.read_chunk_len()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 133, in read_chunk_len
    raise IOError("Invalid chunk header")
OSError: Invalid chunk header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 131, in read_chunk_len
    _len = int(line.strip(), 16)
ValueError: invalid literal for int() with base 16: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
```

I do not understand what happened.

PS: I tried also the following:
```
curl http://localhost:5000/tesseract-recognize/version
tesseract-recognize 2020.01.10
compiled against PageXML 2019.08.12
compiled against tesseract 4.0.0-beta.1, linked with 4.0.0-beta.1
``` 
Is it correct, that the version is not the same?

**Comment by mauvilsa** [comment]
@nachtgold the versions are correct.

Regarding the error I think the problem is related to the curl command. I can reproduce it by running that same command giving as image some file that does not exist. curl is not smart enough to exit with an error if the file does not exist and does the request anyway giving these weird stack trace. But if the image does exist, it should work without any problem. So please try again making sure that after the `-F images=@` it is a relative or full path to an image that does exist.

**Comment by nachtgold** [comment]
@mauvilsa you are right, I had a typo in the filename.
